version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: saude_mysql_container
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'passaporte_saude'
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psua_senha"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./BackEnd
    container_name: saude_backend_container
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./FrontEnd
    container_name: saude_frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend